# The point of this Dockerfile is to make development easier, by
# not running the custom entrypoint at deploy time, and instead relying on
# the user to execute their code from inside the container


FROM ros:noetic

ARG distro=noetic
ENV DEBIAN_FRONTEND=noninteractive

# Create vortex user
RUN useradd -ms /bin/bash \
    --home /home/vortex  vortex
RUN echo "vortex:vortex" | chpasswd
RUN usermod -aG sudo vortex

# ROS package dependencies
RUN apt update && \
    apt install -y \
    ros-$distro-roslint \
    ros-$distro-move-base-msgs \
    ros-$distro-tf \
    ros-$distro-tf2 \
    ros-$distro-smach-ros \
    ros-$distro-eigen-conversions \
    libeigen3-dev \
    ros-$distro-joy \
    ros-$distro-tf2-geometry-msgs \
    ros-$distro-geographic-msgs \
    ros-$distro-pcl-ros \
    ros-$distro-rviz \
    ros-$distro-rtabmap \
    ros-$distro-rtabmap-ros \
    ros-noetic-imu-tools \
    libeigen3-dev \
    libglfw3-dev \
    libglew-dev \
    libjsoncpp-dev \
    libtclap-dev \
    libgeographic-dev \
    python3-catkin-tools \
    python3-vcstool \
    net-tools \     
    tcpdump 

RUN echo "source /opt/ros/noetic/setup.bash" >> /home/vortex/.bashrc
RUN echo "source /home/vortex/asv_ws/devel/setup.bash" >> /home/vortex/.bashrc

RUN mkdir -p /home/vortex/asv_ws
RUN chown vortex /home/vortex/asv_ws

CMD ["/bin/bash"]
