version: '3.8'
services:

  asv:
    image: ghcr.io/vortexntnu/vortex-asv:main
    container_name: asv
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host

  asv-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: asv-dev
    user: vortex
    privileged: true
    volumes:
      - ".:/home/vortex/asv_ws/src/Vortex-ASV" # Shared volume to avoid rebuilding when starting a new container
      - "/dev:/dev"
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host

  lidar:
    image: ghcr.io/vortexntnu/ouster_lidar_driver:master
    command: 
      - "sensor_hostname:=XXX.XXX.XXX.XXX"
      - "metadata:=/lidar_metadata"
    container_name: lidar
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host

  simulator:
    image: ghcr.io/vortexntnu/asv-simulator:main
    container_name: simulator
    user: vortex
    privileged: true
    volumes:
      - "/dev:/dev"
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host
