


version: '3.8'
services:
  asv-dev:
    container_name: asv
    build: .
    privileged: true  
    user: vortex
    volumes:
      - ".:/home/vortex/asv_ws/src/Vortex-ASV" # Shared volume to avoid rebuilding when starting a new container
      - "/dev:/dev"    
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host

  simulator:
    image: ghcr.io/vortexntnu/asv-simulator:main
    container_name: simulator
    stdin_open: true
    tty: true
    network_mode: host
    
  simulator-dev:
    build:
      context: ../ASV-Simulator
      dockerfile: Dockerfile.dev
    container_name: simulator-dev
    user: vortex
    privileged: true
    volumes:
      - "../ASV-Simulator:/home/vortex/sim_ws/src/ASV-Simulator" 
      - "./vortex_msgs:/home/vortex/sim_ws/src/vortex_msgs" 
      - "/dev:/dev"
    entrypoint: /bin/bash
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host