version: '3.8'
services:
  asv:
    image: ghcr.io/vortexntnu/vortex-asv:main
    container_name: asv
    environment:
      DISPLAY: :0
    volumes:
      - /dev:/dev
    stdin_open: true
    tty: true
    network_mode: host
  
  lidar:
    image: ghcr.io/vortexntnu/ouster_lidar_driver:master
    command: 
      - "sensor_hostname:=XXX.XXX.XXX.XXX"
      - "metadata:=/lidar_metadata"
    container_name: lidar
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host

  simulator:
    image: ghcr.io/vortexntnu/asv-simulator:main
    container_name: simulator
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host