map_manager_node:
  ros__parameters:
    use_predef_landmask: false
    map_resolution: 0.2
    map_width: 1000
    map_height: 1000
    frame_id: "world"
    map_origin_lat: 0.0
    map_origin_lon: 0.0
    use_predef_map_origin: false
