map_manager_node:
  ros__parameters:
    use_predef_landmask: true
    landmask_file: "src/vortex-asv/asv_setup/config/sitaw/land_polygon_office.yaml"
    map_resolution: 0.2
    map_width: 1000
    map_height: 1000
    frame_id: "map"
