# This file defines the ROS topics used by the packeges in Vortex-ASV

asv:
  thruster_manager:
    input: "/thrust/desired_forces" # 3DOF thrust vector
    output: "/thrust/thruster_forces" # Actuator forces

task_manager:
  server: "/task_manager/task_manager_server"