failsafe:
  publishers:
    failSafeStatus: '/failSafeStatus'
    hardwareOperationMode: '/hardWareOperationMode'
  subscribers:
    softWareKillSwitch: '/softWareKillSwitch'
    softWareOperationMode: '/softWareOperationMode'

  gpio:
    gpioSoftWareKillSwitch: 33      #pin 33
    gpioSoftWareOperationMode: 31    #pin 31
    gpioFailSafeStatus: 35         #pin 35
    gpioHardWareOperationMode: 29   #pin 29