failsafe:
  publishers:
    failSafeStatus: '/failSafeStatus'
    hardwareOperationMode: '/hardWareOperationMode'
  subscribers:
    softWareKillSwitch: '/softWareKillSwitch'
    softWareOperationMode: '/softWareOperationMode'

  gpio:
    gpioSoftWareKillSwitch: 13      #pin 33
    gpioSoftWareOperationMode: 18    #pin 31
    gpioFailSafeStatus: 15         #pin 35
    gpioHardWareOperationMode: 16   #pin 29