failsafe:
  publishers:
    failSafeStatus: '/failSafeStatus'
    hardwareOperationMode: '/hardWareOperationMode'
  subscribers:
    softWareKillSwitch: '/softWareKillSwitch'
    softWareOperationMode: '/softWareOperationMode'

  gpio:
    gpioSoftWareKillSwitch: 76      #pin 33
    gpioSoftWareOperationMode: 73    #pin 31
    gpioFailSafeStatus: 133         #pin 35
    gpioHardWareOperationMode: 74   #pin 29