# This file defines parameters specific to Freya
#
# When looking at the ASV from above, the thruster placement is:   
#    /\          /\
#   /  \  front /  \
#  /    \      /    \
#  |=3↗=|      |=0↖=|
#  |    |      |    |
#  |    |      |    |
#  |    |======|    |
#  |    |      |    |
#  |    |      |    |
#  |    |      |    |
#  |=2↖=|==||==|=1↗=|
#
/**:
  ros__parameters:
    physical:
      mass_kg: 0 
      displacement_m3: 0
      buoyancy: 0   # kg
      center_of_mass: [0, 0, 0]        # mm (x,y,z)
      center_of_buoyancy: [0, 0, 0]   # mm (x,y,z)
      inertia_matrix: [90.5, 0.0, 0.0, 0.0, 167.5, 12.25, 0.0, 12.25, 42.65] # from otter
      damping_matrix_diag: [77.55, 162.5, 42.65] # from otter


    propulsion:
      dofs:
        num: 3
        which:
          surge: true
          sway:  true
          yaw:   true
      thrusters:
        num: 4
        min: -1000
        max: 1000
        configuration_matrix: #NED
          [0.70711, 0.70711, 0.70711, 0.70711, 
          -0.70711, 0.70711, -0.70711, 0.70711, 
          -0.8485, -0.8485, 0.8485, 0.8485]

        rate_of_change:
          max: 0 # Maximum rate of change in newton per second for a thruster

        thruster_to_pin_mapping: [3, 2, 1, 0] # I.e. if thruster_to_pin = [1, 3, 2, 0] then thruster 0 is pin 1 etc..
        thruster_direction: [-1, 1, 1,-1] # Disclose during thruster mapping (+/- 1)
        thruster_PWM_offset: [0, 0, 0, 0] # Disclose during thruster mapping, Recomended: [0, 0, 0, 0]
        thruster_PWM_min: [1100, 1100, 1100, 1100] # Minimum PWM value, Recomended: [1100, 1100, 1100, 1100]
        thruster_PWM_max: [1900, 1900, 1900, 1900] # Maximum PWM value, Recomended: [1900, 1900, 1900, 1900]
      command:
        wrench:
          max:     [150.0, 150.0, 150.0, 150.0, 150.0, 150.0]
          scaling: [ 1.0,  1.0,  1.0, 1.0, 1.0, 1.0]

    blackbox:
      data_logging_rate: 5.0 # [logings/second], Recomended: 5.0 logings per second
    
    internal_status:
      psm_read_rate: 2.0 # [readings/second], Recomended 2.0 readings per second OBS! Try keeping under 2.0 as otherwise I2C comunication to Power Sense Module might become bad as psm needs time to sample data

    acoustics:
      frequencies_of_interest: # MUST be 20 elements [FREQUENCY [Hz], FREQUENCY_VARIANCE [Hz]...] Recoended: Frequency 1 000 - 50 000 Hz, Variance 1 000 - 10 000
       [10000, 1000,
        50000, 3000,
        0, 0,
        0, 0,
        0, 0,
        0, 0,
        0, 0,
        0, 0,
        0, 0,
        0, 0]
      data_logging_rate: 1.0 # [logings/second], Recomended: 1.0 logings per second

    computer: "pc-debug"
