# This file defines parameters specific to Freya
#
# When looking at the ASV from above, the thruster placement is:   
#    /\          /\
#   /  \  front /  \
#  /    \      /    \
#  |=3↗=|      |=0↖=|
#  |    |      |    |
#  |    |      |    |
#  |    |======|    |
#  |    |      |    |
#  |    |      |    |
#  |    |      |    |
#  |=2↖=|==||==|=1↗=|
#
/**:
  ros__parameters:
    physical:
      mass_kg: 0 
      displacement_m3: 0
      buoyancy: 0   # kg
      center_of_mass: [0, 0, 0]        # mm (x,y,z)
      center_of_buoyancy: [0, 0, 0]   # mm (x,y,z)


    propulsion:
      dofs:
        num: 3
        which:
          surge: true
          sway:  true
          yaw:   true
      thrusters:
        num: 4
        min: -100
        max: 100
        configuration_matrix: #NED
          [0.70711, 0.70711, 0.70711, 0.70711, 
          -0.70711, 0.70711, -0.70711, 0.70711, 
          0.27738, 0.27738, -0.27738, -0.27738]

        rate_of_change:
          max: 0 # Maximum rate of change in newton per second for a thruster
        thruster_to_pin_map: [1, 3, 2, 0] # I.e. if thruster_to_pin = [1, 3, 2, 0] then thruster 0 is pin 1 etc..
        direction: [1, 1, 1, 1] # Disclose during thruster mapping
        offset: [0, 0, 0, 0] # Disclose during thruster mapping
      command:
        wrench:
          max:     [150.0, 150.0, 150.0, 150.0, 150.0, 150.0]
          scaling: [ 1.0,  1.0,  1.0, 1.0, 1.0, 1.0]

    blackbox:
      data_logging_rate: 5.0 # Log all data 5 times per second

    computer: "pc-debug"
