name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        builder: ${{ steps.buildx.outputs.name }}
        tags: "vortex-asv:latest"
        load: true

    - name: Upload image artifact
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "vortex-asv:latest"
