name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: geiger/black-action@master
        with:
          args: ". --check"
          
